//get all posts
GET http://localhost:3000/posts

###
//get all posts by sender
GET http://localhost:3000/posts?sender=Omer

###

//create a post
POST http://localhost:3000/posts
content-type: application/json

{
    "title" : "Post title",
    "content" : "Post content",
    "owner" : "Guy"
}

###

//get post by ID
GET http://localhost:3000/posts/479b845fd4c161f6074aba39

###

//update post by ID
PUT http://localhost:3000/posts/679b83cfd4c161f6074aba21
content-type: application/json

{
    "title" : "Updated posghjkt title",
    "content" : "Updated post content"
}

###

//delete post by ID
DELETE http://localhost:3000/posts/679b8400d4c161f6074aba2c
