//get all posts
GET http://localhost:3000/posts

###
//get all posts by sender
GET http://localhost:3000/posts?sender=Omer

###

//create a post
POST http://localhost:3000/posts
content-type: application/json

{
    "name": "Test Name",
    "post": "Testing post"
}

###

//get post by ID
GET http://localhost:3000/posts/1234

###

//update post by ID
PUT http://localhost:3000/posts/1234
content-type: application/json

{
    "updatedPost": "Updated post content"
}

