//get all posts
GET http://localhost:3000/posts

###
//get all posts by sender
GET http://localhost:3000/posts?sender=Omer

###

//create a post
POST http://localhost:3000/posts
content-type: application/json

{
    "title" : "Post title",
    "content" : "Post content",
    "owner" : "Omer"
}

###

//get post by ID
GET http://localhost:3000/posts/679a3558aef17e57dfd9e786

###

//update post by ID
PUT http://localhost:3000/posts/679a35d7aef17e57dfd9e7a1
content-type: application/json

{
    "title" : "Updated post title",
    "content" : "Updated post content"
}

###

//delete post by ID
DELETE http://localhost:3000/posts/679a35d7aef17e57dfd9e7a1
